site_name: SSIAMB Documentation
site_description: SSI Ambiguous Site Detection Tool
site_url: https://ssi-dk.github.io/ssiamb/
repo_url: https://github.com/ssi-dk/ssiamb
repo_name: ssi-dk/ssiamb
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - API Reference: reference/index.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            merge_init_into_class: true
            show_submodules: false
          paths: [src]

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true

watch:
  - src/ssiamb

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ssi-dk/ssiamb