name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        activate-environment: env
        environment-file: environment.yml
        use-mamba: true
        
    - name: Configure conda channels
      shell: bash -l {0}
      run: |
        # Remove defaults channel and ensure only conda-forge and bioconda are used
        conda config --remove channels defaults || true
        conda config --add channels conda-forge
        conda config --add channels bioconda
        conda config --set channel_priority strict
        conda config --show channels
        
    - name: Install package in development mode
      shell: bash -l {0}
      run: |
        pip install -e .
        
    - name: Lint with ruff
      shell: bash -l {0}
      run: |
        ruff check .
        black --check --diff .
        mypy src/ssiamb
        
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --cov=src/ssiamb --cov-report=term-missing tests/ -v

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build docs
      run: |
        pip install mkdocs mkdocs-material mkdocs-autorefs 'mkdocstrings[python]'
        mkdocs build --clean